### ISSUE TITLE
No User Manual link

### ISSUE THREAD

**Issue by DanGarman** [CuteFoxModules/CuteFoxModules#1]
The menu item "User manual" of your module should target https://github.com/CuteFoxModules/CuteFoxModules . I found it, but not as easily as with a link packaged with the module. Nice idea, btw, thanks

**Comment by CuteFoxModules** [comment]
I've changed it to link to the readme directly.
It should be working correctly by the next library plugin update.
Thanks for the tip and glad you found the module useful!
